site:
  title:  Foundations: kn workflow CLI, Quarkus project structure, and local execution.
  start_page: serverless_logic_sudhish::index.adoc

content:
  sources:
  - url: ./

asciidoc:
  attributes:
    page-pagination: true

ui:
  bundle:
    url: ./ui-bundle/ui-bundle.zip
  supplemental_files: ./supplemental-ui
